/**
 * Todo Lists System API
 * This API exposes endpoints to manage todos / users / etc.
 *
 * OpenAPI spec version: 1.0
 * Contact: mblotiu.ss@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class TagDTO {
    'name'?: string;
    'todoId'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "todoId",
            "baseName": "todoId",
            "type": "number",
            "format": "int64"
        }    ];

    static getAttributeTypeMap() {
        return TagDTO.attributeTypeMap;
    }

    public constructor() {
    }
}

