/**
 * Todo Lists System API
 * This API exposes endpoints to manage todos / users / etc.
 *
 * OpenAPI spec version: 1.0
 * Contact: mblotiu.ss@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class TodoDTO {
    'title'?: string;
    'description'?: string;
    'isCompleted'?: boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "title",
            "baseName": "title",
            "type": "string",
            "format": ""
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "isCompleted",
            "baseName": "isCompleted",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return TodoDTO.attributeTypeMap;
    }

    public constructor() {
    }
}

